spring:
  datasource:
    url: jdbc:mysql://${CA_DATABASE_HOST:192.168.125.1001}:${CA_DATABASE_PORT:3307}/${CA_DATABASE_NAME:jfaster}?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
    username: ${CA_DATABASE_USERNAME:root}
    password: ${CA_DATABASE_PASSWORD:root20180315}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    generate-ddl: true
    database: mysql
    database_platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  http:
    encoding:
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 1073741824MB
      max-request-size: 1073741824MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: true
    time-zone: GMT+8

logging:
  config:
    classpath: logback-spring.xml
server:
  port: 8080